Repository Dharunprakash/hall-plan, pull requests merged in 2025-03, with the labels that each got.

#4 Hall plan string to Enum
  hooks/use-select-hall-type.ts
  prisma/schema.prisma
  schemas/generate-hall/input-schema.ts
  server/actions/index.ts
Labels: GTM, Reviewed

#5 fix: removed get query inside the txn
  server/actions/index.ts
Labels: bug, GTM, Reviewed

#9 Added Input Transformer to change Algo
  lib/hall/student.ts
  lib/utils/GroupedStudent.ts
  lib/utils/criteria.ts
  server/plan.ts
Labels: feature
